### ISSUE TITLE
v2.2

### ISSUE THREAD

**Issue by andris9** [nodemailer/nodemailer#560]
This is the tracking issue for the next Nodemailer version, v2.2.0.

Planned release date: N/A

Planned features/updates (might change):

  - [x] Add some kind of an option to use proxies when connecting to SMTP servers. This has been asked a lot through the years but currently it is not even possible to add a custom proxy handler without overwriting the SMTP modules. I'm not sure if I'm going to add full-blown proxy support right away but the option to add custom socket handlers should be available. Related issue: #555 (*v2.2.0-beta.2*)
  - [x] Better calendar (ICS) support. There has been several complaints about ICS calendar handling (must be alternative, not an attachment). I'm not sure at this point what is actually wrong in the handling or is there something wrong at all, maybe it's just a configuration issue. Related issue: #559 (*v2.2.0-beta.1*)
  - [x] Configuration validator. An utility function that can be called to see if current transport object can actually connect and log in to the SMTP server or not. Should also check for problems with TLS etc. (Idea borrowed from [here](https://github.com/PHPMailer/PHPMailer/issues/612)). (*v2.2.0-beta.6*)
  - [x] ~~Add new transport type: IMAP. Useful when uploading sent messages to the Sent folder in IMAP.~~ this should be handled by an external plugin, related issue: #561
  - [x] Allow sending pre-generated mime messages. Instead of taking input object amd converting it to a rfc822 mime message, take a string or Buffer as an input and pass it directly to SMTP. This is mostly useful for testing (*v2.2.0-beta.0*)
  - [x] Add helpers for the List-* headers. Instead of formatting headers manually, just provide the values (*v2.2.0-beta.5*)
  - [x] Do not blindly use quoted-printable for everything. Quoted-printable makes no sense for non-latin alphabet languages (*v2.2.0-beta.2*)
  - [x] Always prefer STARTTLS for direct connections, fallback to plaintext if STARTTLS fails (*v2.2.0-beta.6*)

**Comment by andris9** [comment]
Added new message option `raw` to be able to send pre-generated mime messages. Released as v2.2.0-beta.0

Install with `npm install nodemailer@beta`

```javascript
transport.sendMail({
    raw: 'Content-Type: text/plain\r\nSubject: Test\r\n\r\nHello world!',
    // envelope needs to be set as raw is not processed
    envelope: {
        from: 'sender@example.com',
        to: 'receiver@example.com'
    }
});
```

**Comment by andris9** [comment]
Released v2.2.0-beta.1 that adds new message option `icalEvent` for using embedded iCalendar events.

```javascript
var message = {
    from: '"Sender Name" <sender@example.com>',
    to: '"Receiver Name" <receiver@example.com>',
    subject: 'Calendar invite',
    text: 'This message contains a calendar event',
    icalEvent: {
        method: 'request',
        // content can be a string, a buffer or a stream
        // alternatively you could use `path` that points to a file or an url
        content: 'BEGIN:VCALENDAR\r\nPRODID:-//ACME/DesktopCalendar//EN\r\n...'
    }
};
```

**Comment by andris9** [comment]
Released v2.2.0-beta.2 that adds support for proxied sockets. See full example for using SOCKS5 [here](https://github.com/nodemailer/nodemailer/blob/v2.2/examples/proxy.js).

Nodemailer does not have built-in knowledge about different proxy protocols. Instead it provides a mechanism for using custom sockets which can be created with some proxy module, eg. [socks](https://www.npmjs.com/package/socks).

```javascript
transporter.getSocket = function(options, callback){
    getNewSocketSomehow(options.port, options.host, function(err, socket){
        if(err){
            return callback(err);
        }
        callback(null, {
            connection: socket
        });
    });
};
```

**Comment by andris9** [comment]
v2.2.0-beta.5 has support for List-\* headers

```javascript
var mailOptions = {
    list: {
        // List-Help: <mailto:admin@example.com?subject=help>
        help: 'admin@example.com?subject=help',
        // List-Unsubscribe: <http://example.com> (Comment)
        unsubscribe: {
            url: 'http://example.com',
            comment: 'Comment'
        },
        // List-Subscribe: <mailto:admin@example.com?subject=subscribe>
        // List-Subscribe: <http://example.com> (Subscribe)
        subscribe: [
            'admin@example.com?subject=subscribe',
            {
                url: 'http://example.com',
                comment: 'Subscribe'
            }
        ],
        // List-Post: <http://example.com/post>, <mailto:admin@example.com?subject=post> (Post)
        post: [
            [
                'http://example.com/post',
                {
                    url: 'admin@example.com?subject=post',
                    comment: 'Post'
                }
            ]
        ]
    }
};
```

**Comment by andris9** [comment]
I'm not sure anymore that the List-\* thing should be built into Nodemailer, I should probably consider moving it into a plugin instead.

**Comment by andris9** [comment]
Released *v2.2.0-beta.1* with simple configuration verifier

```javascript
// verify connection configuration
transporter.verify(function(error, success) {
   if (error) {
        console.log(error);
   } else {
        console.log('Server is ready to take our messages');
   }
});
```

**Comment by andris9** [comment]
I have closed all the issues related to v2.2, so I can publish a rc version. Probably going to wait until tomorrow with the rc in case I'm going to have some new ideas of what to put into this release.

**Comment by andris9** [comment]
Released v2.2.0-rc.7. Expected stable release date: February 19.

**Comment by andris9** [comment]
v2.2.0-rc.7 makes the dependency tree a bit smaller as there is no need for [clone](https://www.npmjs.com/package/clone) anymore. Instead a more simpler homegrown method is used that only makes shallow copies

**Comment by andris9** [comment]
Stable release was planned for tomorrow but I don't have time for it then, so I published v2.2.0 already today.

Release blog post can be found [here](http://nodemailer.com/nodemailer-v2-2/)

**Comment by bertho-zero** [comment]
How to convert _List-*_ headers now ?

**Comment by bertho-zero** [comment]
I am not able to add a comment containing an accent to my List-Unsubscribe header, I do not see how to encode it with the current version of nodemailer.
